gcc-env:
  compiler: [gcc]
  network:
      mpi: cray-mpich@8.1.32 +cuda
      specs:
      - libfabric@2.3 +gdrcopy
  unify: true
  specs:
  - boost +chrono +filesystem +iostreams +mpi +python +regex +serialization +shared +system +timer +thread
  - cmake
  - fmt
  - hdf5+cxx+hl+fortran
  - netcdf-c
  - netcdf-cxx
  - netcdf-cxx4
  - netcdf-fortran
  - ninja
  - openblas threads=openmp
  - osu-micro-benchmarks
  - python
  - py-pybind11
  - py-pip
  # add GPU-specific packages here, for easier comparison with mc version
  - nccl
  - nccl-tests
  - cuda
  - xcb-util-cursor
  - aws-ofi-nccl
  variants:
  - +mpi
  - +cuda
  - cuda_arch=90a
  views:
    default:
      link: roots
      uenv:
        add_compilers: true
        prefix_paths:
          LD_LIBRARY_PATH: [lib, lib64]
